### ISSUE TITLE
Failed to install Proton IDE. Failed at the runas@0.5.4 install script

### ISSUE THREAD

**Issue by magandrez** [haggy/Proton-IDE#8]
Hi

I was trying to install this package when I bumped into this error: 

```
> runas@0.5.4 install /private/var/folders/yv/jbqbhrtn3zlgmwglqkm1q5nw0000gn/T/apm-install-dir-11482-1697-w201rw/node_modules/Proton-IDE/node_modules/text-buffer/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

  CXX(target) Release/obj.target/runas/src/main.o

npm http GET https://registry.npmjs.org/jQuery
npm http GET https://registry.npmjs.org/fs-plus
npm http GET https://registry.npmjs.org/node-rest-client
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/text-buffer/2.4.0
npm http GET https://registry.npmjs.org/soap
npm http GET https://registry.npmjs.org/xml2js
npm http GET https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/node-rest-client
npm http 304 https://registry.npmjs.org/fs-plus
npm http 304 https://registry.npmjs.org/jQuery
npm WARN deprecated jQuery@1.7.4: This is deprecated. Please use 'jquery' (all lowercase).
npm http 304 https://registry.npmjs.org/xml2js
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/soap
npm http 304 https://registry.npmjs.org/text-buffer/2.4.0
npm http 304 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/span-skip-list
npm http GET https://registry.npmjs.org/delegato
npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/grim/0.11.0
npm http GET https://registry.npmjs.org/interval-skip-list
npm http GET https://registry.npmjs.org/serializable
npm http GET https://registry.npmjs.org/pathwatcher
npm http GET https://registry.npmjs.org/q
npm http GET https://registry.npmjs.org/xmlbuilder
npm http GET https://registry.npmjs.org/sax
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/sax
npm http GET https://registry.npmjs.org/strip-bom
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/grim/0.11.0
npm http 304 https://registry.npmjs.org/span-skip-list
npm http 304 https://registry.npmjs.org/interval-skip-list
npm http 304 https://registry.npmjs.org/delegato
npm http 304 https://registry.npmjs.org/q
npm http 304 https://registry.npmjs.org/pathwatcher
npm http 304 https://registry.npmjs.org/xmlbuilder
npm http 304 https://registry.npmjs.org/sax
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/sax
npm http 304 https://registry.npmjs.org/serializable
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/lodash-node
npm http 304 https://registry.npmjs.org/emissary
npm http 304 https://registry.npmjs.org/strip-bom
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/get-parameter-names
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/first-chunk-stream
npm http GET https://registry.npmjs.org/is-utf8
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/lodash-node
npm http GET https://registry.npmjs.org/property-accessors
npm http GET https://registry.npmjs.org/runas
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/nan/0.8.0
npm http GET https://registry.npmjs.org/mime-types
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/forever-agent
npm http GET https://registry.npmjs.org/tough-cookie
npm http GET https://registry.npmjs.org/form-data
npm http GET https://registry.npmjs.org/tunnel-agent
npm http GET https://registry.npmjs.org/http-signature
npm http GET https://registry.npmjs.org/oauth-sign
npm http 304 https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/hawk/1.1.1
npm http GET https://registry.npmjs.org/aws-sign2
npm http GET https://registry.npmjs.org/stringstream
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/json-stringify-safe
npm http 304 https://registry.npmjs.org/first-chunk-stream
npm http 304 https://registry.npmjs.org/get-parameter-names
npm http 304 https://registry.npmjs.org/property-accessors
npm http 304 https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/testla
npm http 304 https://registry.npmjs.org/mime-types
npm http 304 https://registry.npmjs.org/runas
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/is-utf8
npm http 304 https://registry.npmjs.org/forever-agent
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/tough-cookie
npm http 304 https://registry.npmjs.org/form-data
npm http 304 https://registry.npmjs.org/http-signature
npm http 304 https://registry.npmjs.org/tunnel-agent
npm http 304 https://registry.npmjs.org/oauth-sign
npm http 304 https://registry.npmjs.org/hawk/1.1.1
npm http 304 https://registry.npmjs.org/aws-sign2
npm http 304 https://registry.npmjs.org/json-stringify-safe
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/stringstream
npm http GET https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/testla
npm http GET https://registry.npmjs.org/assert-plus/0.1.2
npm http GET https://registry.npmjs.org/asn1/0.1.11
npm http GET https://registry.npmjs.org/ctype/0.5.2
npm http 304 https://registry.npmjs.org/nan/0.8.0
npm http 304 https://registry.npmjs.org/ctype/0.5.2
npm http GET https://registry.npmjs.org/dependency-injector
npm http GET https://registry.npmjs.org/fantasy-promises
In file included from ../src/main.cc:1:
../../nan/nan.h:339:13: error: no member named 'New' in 'v8::String'
    return  _NAN_ERROR(v8::Exception::Error, errmsg);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
../../nan/nan.h:343:5: error: no member named 'ThrowException' in namespace 'v8'
    _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:324:11: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
      ~~~~^
../../nan/nan.h:343:5: error: no member named 'New' in 'v8::String'
    _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:324:26: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
                         ^~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
../../nan/nan.h:348:9: error: no type named 'ThrowException' in namespace 'v8'
    v8::ThrowException(error);
    ~~~~^
../../nan/nan.h:355:65: error: no member named 'New' in 'v8::String'
    v8::Local<v8::Value> err = v8::Exception::Error(v8::String::New(msg));
                                                    ~~~~~~~~~~~~^
../../nan/nan.h:357:26: error: no member named 'New' in 'v8::String'
    obj->Set(v8::String::New("code"), v8::Int32::New(errorNumber));
             ~~~~~~~~~~~~^
../../nan/nan.h:369:12: error: no member named 'New' in 'v8::String'
    return _NAN_ERROR(v8::Exception::TypeError, errmsg);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
../../nan/nan.h:373:5: error: no member named 'ThrowException' in namespace 'v8'
    _NAN_THROW_ERROR(v8::Exception::TypeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:324:11: note: expanded from macro '_NAN_THROW_ERROR'

      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
      ~~~~^
../../nan/nan.h:373:5: error: no member named 'New' in 'v8::String'
    _NAN_THROW_ERROR(v8::Exception::TypeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:324:26: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
                         ^~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
../../nan/nan.h:377:12: error: no member named 'New' in 'v8::String'
    return _NAN_ERROR(v8::Exception::RangeError, errmsg);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
../../nan/nan.h:381:5: error: no member named 'ThrowException' in namespace 'v8'
    _NAN_THROW_ERROR(v8::Exception::RangeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:324:11: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
      ~~~~^
../../nan/nan.h:381:5: error: no member named 'New' in 'v8::String'
    _NAN_THROW_ERROR(v8::Exception::RangeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:324:26: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
                         ^~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
../../nan/nan.h:727:49: error: too few arguments to function call, single argument 'isolate' was not specified
    v8::Local<v8::Object> obj = v8::Object::New();
                                ~~~~~~~~~~~~~~~ ^
/Users/spav/.atom/.node-gyp/.node-gyp/0.11.13/deps/v8/include/v8.h:2372:3: note: 'New' declared here
  static Local<Object> New(Isolate* isolate);
  ^
In file included from ../src/main.cc:1:
../../nan/nan.h:733:49: error: too few arguments to function call, single argument 'isolate' was not specified
    v8::Local<v8::Object> obj = v8::Object::New();
                                ~~~~~~~~~~~~~~~ ^
/Users/spav/.atom/.node-gyp/.node-gyp/0.11.13/deps/v8/include/v8.h:2372:3: note: 'New' declared here
  static Local<Object> New(Isolate* isolate);
  ^
In file included from ../src/main.cc:1:
../../nan/nan.h:740:12: error: no member named 'Dispose' in 'v8::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
    handle.Dispose();
    ~~~~~~ ^
../../nan/nan.h:741:12: error: no member named 'Clear' in 'v8::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
    handle.Clear();
    ~~~~~~ ^
../../nan/nan.h:746:39: error: no member named 'NewSymbol' in 'v8::String'; did you mean 'IsSymbol'?
    NanPersistentToLocal(handle)->Set(NanSymbol("callback"), fn);
                                      ^~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:181:38: note: expanded from macro 'NanSymbol'
#define NanSymbol(value) v8::String::NewSymbol(value)
                         ~~~~~~~~~~~~^
/Users/spav/.atom/.node-gyp/.node-gyp/0.11.13/deps/v8/include/v8.h:1356:8: note: 'IsSymbol' declared here
  bool IsSymbol() const;
       ^
In file included from ../src/main.cc:1:
../../nan/nan.h:746:39: error: call to non-static member function without an object argument
    NanPersistentToLocal(handle)->Set(NanSymbol("callback"), fn);
                                      ^~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:181:38: note: expanded from macro 'NanSymbol'
#define NanSymbol(value) v8::String::NewSymbol(value)
                         ~~~~~~~~~~~~^~~~~~~~~
../../nan/nan.h:750:46: error: no member named 'NewSymbol' in 'v8::String'; did you mean 'IsSymbol'?
    return NanPersistentToLocal(handle)->Get(NanSymbol("callback"))
                                             ^~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:181:38: note: expanded from macro 'NanSymbol'
#define NanSymbol(value) v8::String::NewSymbol(value)
                         ~~~~~~~~~~~~^
/Users/spav/.atom/.node-gyp/.node-gyp/0.11.13/deps/v8/include/v8.h:1356:8: note: 'IsSymbol' declared here
  bool IsSymbol() const;
       ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/runas/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Darwin 13.3.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/yv/jbqbhrtn3zlgmwglqkm1q5nw0000gn/T/apm-install-dir-11482-1697-w201rw/node_modules/Proton-IDE/node_modules/text-buffer/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/combined-stream
npm http 304 https://registry.npmjs.org/assert-plus/0.1.2
npm http 304 https://registry.npmjs.org/asn1/0.1.11
npm http GET https://registry.npmjs.org/punycode
npm http GET https://registry.npmjs.org/delayed-stream/0.0.5
npm http GET https://registry.npmjs.org/hoek
npm http GET https://registry.npmjs.org/boom
npm http GET https://registry.npmjs.org/sntp
npm http GET https://registry.npmjs.org/cryptiles
npm http 304 https://registry.npmjs.org/fantasy-promises
npm http 304 https://registry.npmjs.org/boom
npm http 304 https://registry.npmjs.org/punycode
npm http 304 https://registry.npmjs.org/delayed-stream/0.0.5
npm http 304 https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/cryptiles
npm http 304 https://registry.npmjs.org/dependency-injector
npm http 304 https://registry.npmjs.org/hoek
npm ERR! runas@0.5.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@0.5.4 install script.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.3.0
npm ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/.apmrc" "--userconfig" "/Users/spav/.atom/.apmrc" "install" "/Users/spav/.atom/.node-gyp/.atom/.apm/Proton-IDE/0.10.0/package.tgz" "--target=0.11.13" "--arch=x64"
npm ERR! cwd /private/var/folders/yv/jbqbhrtn3zlgmwglqkm1q5nw0000gn/T/apm-install-dir-11482-1697-w201rw
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.4
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /private/var/folders/yv/jbqbhrtn3zlgmwglqkm1q5nw0000gn/T/apm-install-dir-11482-1697-w201rw/npm-debug.log
npm ERR! not ok code 0

```

I know you are not the developer for that package mentioned in the debug, but I thought you might have more information on this.

Let me know if I can help on anything.

**Comment by haggy** [comment]
Hi @magandrez 

Sorry I have been away for business for a couple weeks. I'm just returning now. Can you tell me where this error happened in your process of installing proton?

**Comment by magandrez** [comment]
Hi @haggy 

Sure, no rush. It was when installing the package. My previous comment contains the full log from that attempt.

**Comment by patrickjamesbarry** [comment]
Failed to install for me as well. With a fresh install of Atom.io, this was the first package I tried to install.

**Comment by ZergyPoo** [comment]
Failed to install for me just now.

**Comment by haggy** [comment]
Sorry I've been unresponsive about these issues, development on this has halted because Mavens is coming out with an atom plugin using their popular, reliable SFDC app. It will be great when it comes online!

@ZergyPoo , @patrickjamesbarry , @magandrez

**Comment by gwarburton** [comment]
@haggy Mavens atom plugin?  Neat!

**Comment by andrew-chiz-muzychuk** [comment]
Can't install.
Run Atom. Go to Install Packages. Type Proton IDE. Hit Install.

> runas@0.5.4 install C:\Users\Admin\AppData\Local\Temp\apm-install-dir-115221-6196-e4apiv\node_modules\Proton-IDE\node_modules\text-buffer\node_modules\pathwatcher\node_modules\runas
> node-gyp rebuild

C:\Users\Admin\AppData\Local\Temp\apm-install-dir-115221-6196-e4apiv\node_modules\Proton-IDE\node_modules\text-buffer\node_modules\pathwatcher\node_modules\runas>node "C:\Users\Admin\AppData\Local\atom\app-0.187.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild 

npm WARN deprecated jQuery@1.7.4: This is deprecated. Please use 'jquery' (all lowercase).
gypnpm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Users\Admin\AppData\Local\atom\app-0.187.0\resources\app\apm\bin\\node.exe" "C:\Users\Admin\AppData\Local\atom\app-0.187.0\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\Admin\.atom\.apm\.apmrc" "--userconfig" "C:\Users\Admin\.atom\.apmrc" "install" "C:\Users\Admin\AppData\Local\Temp\d-115221-6196-1tmrg2m\package.tgz" "--target=0.21.0" "--arch=ia32"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! runas@0.5.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@0.5.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

Win7 64.

**Comment by dutchchasman** [comment]
I am seeing the same issue as @andrew-chiz-muzychuk reported above

**Comment by dutchchasman** [comment]
I was seeing the same issue - too many links still direct folks to this project instead of https://github.com/joeferraro/MavensMate-Atom that installed perfectly on first try
